//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternetShopAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesInternetShop : DbContext
    {
        public EntitiesInternetShop()
            : base("name=EntitiesInternetShop")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Заказ> Заказ { get; set; }
        public DbSet<Пользователь> Пользователь { get; set; }
        public DbSet<Роль> Роль { get; set; }
        public DbSet<СоставЗаказа> СоставЗаказа { get; set; }
        public DbSet<ТипТовара> ТипТовара { get; set; }
        public DbSet<Товар> Товар { get; set; }
    }
}
