//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternetShopAPI
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Заказ
    {
        public Заказ()
        {
            this.СоставЗаказа = new HashSet<СоставЗаказа>();
        }
    
        public long КодЗаказа { get; set; }
        public Nullable<long> КодПользователя { get; set; }
        public Nullable<decimal> Стоимость { get; set; }
        public string ТипОплаты { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
        public string Статус { get; set; }

        [JsonIgnore]
        public virtual Пользователь Пользователь { get; set; }
        [JsonIgnore]
        public virtual ICollection<СоставЗаказа> СоставЗаказа { get; set; }
    }
}
