//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternetShopAPI
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Пользователь
    {
        public Пользователь()
        {
            this.Заказ = new HashSet<Заказ>();
        }
    
        public long КодПользователя { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public string Телефон { get; set; }
        public string Логин { get; set; }
        public string Пароль { get; set; }
        public Nullable<long> Роль { get; set; }

        [JsonIgnore]
        public virtual ICollection<Заказ> Заказ { get; set; }
        [JsonIgnore]
        public virtual Роль Роль1 { get; set; }
    }
}
