//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternetShopAPI
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class СоставЗаказа
    {
        public long КодСоставаЗаказа { get; set; }
        public string Наименование { get; set; }
        public Nullable<long> ТоварКодТовара { get; set; }
        public Nullable<long> ЗаказКодЗаказа { get; set; }

        [JsonIgnore]
        public virtual Заказ Заказ { get; set; }
        [JsonIgnore]
        public virtual Товар Товар { get; set; }
    }
}
