//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternetShopAPI
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class ТипТовара
    {
        public ТипТовара()
        {
            this.Товар = new HashSet<Товар>();
        }
    
        public long КодТипа { get; set; }
        public string Наименование { get; set; }

        [JsonIgnore]
        public virtual ICollection<Товар> Товар { get; set; }
    }
}
