//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternetShopAPI
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Товар
    {
        public Товар()
        {
            this.СоставЗаказа = new HashSet<СоставЗаказа>();
        }
    
        public long КодТовара { get; set; }
        public string Название { get; set; }
        public string Производитель { get; set; }
        public Nullable<decimal> Цена { get; set; }
        public Nullable<int> Количество { get; set; }
        public Nullable<long> Тип { get; set; }
    
        [JsonIgnore]       
        public virtual ICollection<СоставЗаказа> СоставЗаказа { get; set; }
        [JsonIgnore]
        public virtual ТипТовара ТипТовара { get; set; }
    }
}
